version: "3.3"
services:
  app:
    container_name: nextjs-app
    user: "1500:1500"
    hostname: app
    ports:
      - 3000:3000
    build: app
    volumes:
      - ../../:/app
    env_file:
      - ../../.env
